### PR TITLE
stackclub package for library of simple helper modules

### LINKED ISSUE #20: Include python script/module from this repo, packaged up
One of our early "getting started" notebooks should show how to include small python scripts from our suitably-organized DM stack club repo package. This will need the packaging being set up, with `install -develop` etc, and all of that documenting for new users.

### LINKED ISSUE #79: Start experimental module library
... to enable useful functions etc to be kept in small module files and imported as needed. `whereis` (issue #76) is a good first example of this; @jtmyles and I also want to be able to import modules after downloading them from the web. It would be nice to be able to [import notebooks](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Importing%20Notebooks.html) as well (h/t to @jonathansick for that pointer).

Update: This issue turned out to be an epic, with a bunch of issues being addressed by the same PR, #80 
* [ ] #20 Include modules, packaged up (also this issue)
* [ ] #76 Module to help find the source code from inside a notebook
* [ ] #81 API docs for the stackclub library

### PR DESCRIPTION
**Pull request by drphilmarshall**
This PR closes #20 (in which we said it would be good to show how to write python scripts and modules and import them into notebooks). It also closes #79 (in which we said we would start an experimental library of modules). I am not sure the packaging is optimal, but the approach I am trying should let other projects (eg lsst-com/notebooks) use the Stack Club utilities fairly straightforwardly. 

The idea is to keep general purpose functions in modules in the `stackclub` folder, which is an importable package. When working on notebooks in a StackClub repo folder (like Basics), we want to be able to do things like
```
from stackclub import where_is
```
And in fact we want to do this from anywhere - and so making stackclub be an importable (and pip-installable) package seems to be the way to go. The demo for this system is in the [Basics/FindingDocs.ipynb notebook in the issue/79/library branch](https://github.com/LSSTScienceCollaborations/StackClub/blob/issue/79/library/Basics/FindingDocs.ipynb). As you can see, its setup markdown cell contains the following explanation:

> We'll need the stackclub package to be installed. If you are not developing this package, you can install it using pip, like this:
```
pip install git+git://github.com/LSSTScienceCollaborations/StackClub.git#egg=stackclub
```
> If you are developing the stackclub package (eg by adding modules to it to support the Stack Club tutorial that you are writing, you'll need to make a local, editable installation. In the top level folder of the StackClub repo, do
```
python setup.py develop --user
```

To make the notebook run under CIT, I think the ~~former~~ latter pip install command will need to be executable by default.

Comments welcome! I have another utility function in mind, which I will add to this branch - but code review is welcome any time. Asking @SimonKrughoff and/or @kadrlica to take a look at the proposed structure, and see if there's a better way to do this.

### CODE REVIEW

File: setup.py [hunk 1]
```diff
@@ -0,0 +1,24 @@
+from setuptools import setup
+
+setup(# package information
+      name="stackclub",
+      version="0.1",
+      author="Phil Marshall",
+      author_email="dr.phil.marshall@gmail.com",
+      description="Utilities for use in e.g the Stack Club LSST tutorial notebooks",
+      long_description=open("README.md").read(),
```
Comment (kadrlica) [inline setup.py]: Should this be README.rst for beavis?

**Comment by kadrlica** [comment]
I think it's worth having a cell run with `%load ../stackclub/whereis`. I've never seen it, and maybe others haven't as well.

Why did you chose to have this in a new directory and not in GettingStarted?

File: setup.py (hunk 1 above)
Comment (drphilmarshall) [reply setup.py]: Oh - I _think_ this refers to the top level package README, which is still markdown (for now). I think it can stay that way too, unless we think its just better to have only rst README files throughout (for sanity?)

**Comment by drphilmarshall** [comment]
@kadrlica I was not thinking very hard about where the FindingDocs tutorial should live - GettingStarted seems like a better place for it, I agree. Ive moved it, and added the `%load -n where_is` you asked for as well. 

Meanwhile, `Basics` now includes a stub of a data inventory notebook, that imports Jim Chiang's skymap plotting code from his DESC notebook: the `stackclub` library now enables us to a) import modules from the internet, by passing in their URL, and b) import notebooks as if they were modules(!). I think both these features may well be useful. Check out `wimport.py` and `nbimport.py`, suggestions welcome for how best to explain this new functionality beyond the data inventory example.

**Comment by drphilmarshall** [comment]
PS. This PR also closes #76 (finding the source code)
PPS. It should be easy to get the API documentation for the `stackclub` package up at https://stackclub.readthedocs.io/ (I just connected it), we just need a docs folder with an `index.rst` and a sphinx `conf.py`. I'll issue this.

**Comment by drphilmarshall** [comment]
Stack Club package docs are up, at https://stackclub.readthedocs.io/en/issue-79-library - this PR now closes #81 as well :-) What do you think, @kadrlica - is the `stackclub` library in good enough shape to go with?

File: Basics/DataInventory.ipynb [hunk 2]
```diff
@@ -0,0 +1,298 @@
...
+  },
+  {
+   "cell_type": "markdown",
+   "metadata": {
+    "slideshow": {
+     "slide_type": "subslide"
+    }
+   },
+   "source": [
+    "For accessing the datasets using the Butler, and then visualizing the results, we'll need the following modules:"
```
Comment (stargaser) [inline Basics/DataInventory.ipynb]: Due to alphabetical ordering of directories, I started executing this notebook before GettingStarted/FindingDocs.ipynb which describes how to install the stackclub package. I recommend to include a note to look at that notebook or other instructions for installing stackclub.

File: Basics/DataInventory.ipynb [hunk 3]
```diff
@@ -0,0 +1,298 @@
...
+  },
+  {
+   "cell_type": "code",
+   "execution_count": null,
+   "metadata": {},
+   "outputs": [],
+   "source": [
+    "dm_butler_skymap_notebook = \"https://github.com/LSSTDESC/DC2-analysis/raw/master/tutorials/dm_butler_skymap.ipynb\"\n",
+    "\n",
+    "skymapper = stackclub.wimport(dm_butler_skymap_notebook, vb=True)"
```
Comment (stargaser) [inline Basics/DataInventory.ipynb]: For me, this cell results in
```
WARNING: module was downloaded to {} but cound not be imported.
Returning path to module: .downloads/dm_butler_skymap.ipynb
```

and the next cell finds 0 tracts.

File: GettingStarted/FindingDocs.ipynb [hunk 4]
```diff
@@ -0,0 +1,267 @@
...
+    "help(ImageDifferenceTask)"
+   ]
+  },
+  {
+   "cell_type": "code",
+   "execution_count": null,
+   "metadata": {},
+   "outputs": [],
+   "source": [
+    "help(ImageDifferenceTask.run)"
```
Comment (stargaser) [inline GettingStarted/FindingDocs.ipynb]: Using weekly `w_2018_31` I get
```
AttributeError: type object 'ImageDifferenceTask' has no attribute 'run'
```

I'll try this on v16.0 and report back.

Comment (stargaser) [reply GettingStarted/FindingDocs.ipynb]: `help(ImageDifferenceTask.run)` works in v16.0 but not in `w_2018_31` which illustrates that this is changing. See https://community.lsst.org/t/api-change-for-tasks-rename-run-primarymethod-to-rundataref-run/3054 on how this is being renamed to `runDataRef`.

Is there a different example that could be substituted?

File: Basics/DataInventory.ipynb (hunk 3 above)
Comment (stargaser) [reply Basics/DataInventory.ipynb]: I tried the notebook in v16.0 and in `w_2018_31` with the same results -- no tracts found and no plots made.

File: Basics/DataInventory.ipynb (hunk 2 above)
Comment (drphilmarshall) [reply Basics/DataInventory.ipynb]: Oh, good catch. I think the template notebook needs a cell on this, and DataInventory definitely does. I'll do this.

File: Basics/DataInventory.ipynb (hunk 3 above)
Comment (drphilmarshall) [reply Basics/DataInventory.ipynb]: Yup, this is a bug: I don't know why the module could not be imported. I'm thinking to comment out this cell for now, and issue a fix.

File: GettingStarted/FindingDocs.ipynb (hunk 4 above)
Comment (drphilmarshall) [reply GettingStarted/FindingDocs.ipynb]: Good idea - I'll find one. Thanks!
